version: "3.8"

services:
  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - registration-service
      - ai-service

  registration-service:
    build: ./backend/registration-service
    container_name: registration-service
    ports:
      - "8000:8000"
    env_file:
      - ./backend/registration-service/.env
    environment:
      - AI_SERVICE_URL=http://ai-service:5000

  ai-service:
    build: ./backend/AI-service
    container_name: ai-service
    env_file:
      - ./backend/AI-service/.env
  frontend-web:
    build: ./frontend-web
    container_name: frontend-web
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  # frontend-mobile:
  #   build: ./frontend-mobile
  #   container_name: frontend-mobile
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - api-gateway
